/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package project3;

/**
 *
 * @author rosbelsanroman
 */
public class ServerWindow extends javax.swing.JFrame {

    /**
     * Creates new form ServerWindow
     */
    public ServerWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        controlPanel = new javax.swing.JPanel();
        paintButton = new javax.swing.JToggleButton();
        robotSlider = new javax.swing.JSlider();
        jointButtonsPanel = new javax.swing.JPanel();
        j1Label = new javax.swing.JLabel();
        j3RightButton = new javax.swing.JButton();
        j2RightButton = new javax.swing.JButton();
        j2LeftButton = new javax.swing.JButton();
        j3LeftButton = new javax.swing.JButton();
        j1RightButton = new javax.swing.JButton();
        j1LeftButton = new javax.swing.JButton();
        j2Label = new javax.swing.JLabel();
        j3Label = new javax.swing.JLabel();
        upButton = new javax.swing.JButton();
        downButton = new javax.swing.JButton();
        leftButton = new javax.swing.JButton();
        rightButton = new javax.swing.JButton();
        coordinatesPanel = new javax.swing.JPanel();
        jointTitleLabel = new javax.swing.JLabel();
        xTitleLabel = new javax.swing.JLabel();
        yTitleLabel = new javax.swing.JLabel();
        joint1Label = new javax.swing.JLabel();
        joint1XLabel = new javax.swing.JLabel();
        joint1YLabel = new javax.swing.JLabel();
        joint2Label = new javax.swing.JLabel();
        joint2XLabel = new javax.swing.JLabel();
        joint2YLabel = new javax.swing.JLabel();
        joint3Label = new javax.swing.JLabel();
        joint3XLabel = new javax.swing.JLabel();
        joint3YLabel = new javax.swing.JLabel();
        brushLabel = new javax.swing.JLabel();
        brushXLabel = new javax.swing.JLabel();
        brushYLabel = new javax.swing.JLabel();
        clearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        controlPanel.setPreferredSize(new java.awt.Dimension(362, 100));
        controlPanel.setSize(new java.awt.Dimension(200, 100));

        paintButton.setFont(paintButton.getFont().deriveFont(paintButton.getFont().getStyle() | java.awt.Font.BOLD, paintButton.getFont().getSize()+5));
        paintButton.setText("Paint");
        paintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paintButtonActionPerformed(evt);
            }
        });

        j1Label.setText("Joint 1");

        j3RightButton.setText(">");
        j3RightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j3RightButtonActionPerformed(evt);
            }
        });

        j2RightButton.setText(">");
        j2RightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2RightButtonActionPerformed(evt);
            }
        });

        j2LeftButton.setText("<");
        j2LeftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2LeftButtonActionPerformed(evt);
            }
        });

        j3LeftButton.setText("<");
        j3LeftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j3LeftButtonActionPerformed(evt);
            }
        });

        j1RightButton.setText(">");
        j1RightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j1RightButtonActionPerformed(evt);
            }
        });

        j1LeftButton.setText("<");
        j1LeftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j1LeftButtonActionPerformed(evt);
            }
        });

        j2Label.setText("Joint 2");

        j3Label.setText("Joint 3");

        upButton.setText("up");

        downButton.setText("down");

        leftButton.setText("left");
        leftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftButtonActionPerformed(evt);
            }
        });

        rightButton.setText("right");

        javax.swing.GroupLayout jointButtonsPanelLayout = new javax.swing.GroupLayout(jointButtonsPanel);
        jointButtonsPanel.setLayout(jointButtonsPanelLayout);
        jointButtonsPanelLayout.setHorizontalGroup(
            jointButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jointButtonsPanelLayout.createSequentialGroup()
                .addGroup(jointButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jointButtonsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jointButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(j3Label)
                            .addComponent(j2Label)
                            .addComponent(j1Label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jointButtonsPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(leftButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jointButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jointButtonsPanelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(rightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(upButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jointButtonsPanelLayout.createSequentialGroup()
                        .addComponent(j1LeftButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j1RightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jointButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jointButtonsPanelLayout.createSequentialGroup()
                            .addComponent(j3LeftButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(j3RightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jointButtonsPanelLayout.createSequentialGroup()
                            .addComponent(j2LeftButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(j2RightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(downButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jointButtonsPanelLayout.setVerticalGroup(
            jointButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jointButtonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jointButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j3RightButton)
                    .addComponent(j3LeftButton)
                    .addComponent(j3Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jointButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j2RightButton)
                    .addComponent(j2LeftButton)
                    .addComponent(j2Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jointButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j1LeftButton)
                    .addComponent(j1RightButton)
                    .addComponent(j1Label))
                .addGap(18, 18, 18)
                .addComponent(upButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jointButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leftButton)
                    .addComponent(rightButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(downButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        coordinatesPanel.setLayout(new java.awt.GridLayout(5, 3));

        jointTitleLabel.setBackground(new java.awt.Color(200, 200, 200));
        jointTitleLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jointTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jointTitleLabel.setText("Joint");
        coordinatesPanel.add(jointTitleLabel);

        xTitleLabel.setBackground(new java.awt.Color(200, 200, 200));
        xTitleLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        xTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xTitleLabel.setText("X");
        coordinatesPanel.add(xTitleLabel);

        yTitleLabel.setBackground(new java.awt.Color(200, 200, 200));
        yTitleLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        yTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yTitleLabel.setText("Y");
        coordinatesPanel.add(yTitleLabel);

        joint1Label.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        joint1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        joint1Label.setText("1");
        coordinatesPanel.add(joint1Label);

        joint1XLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        joint1XLabel.setText("0");
        coordinatesPanel.add(joint1XLabel);

        joint1YLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        joint1YLabel.setText("0");
        coordinatesPanel.add(joint1YLabel);

        joint2Label.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        joint2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        joint2Label.setText("2");
        coordinatesPanel.add(joint2Label);

        joint2XLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        joint2XLabel.setText("0");
        coordinatesPanel.add(joint2XLabel);

        joint2YLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        joint2YLabel.setText("0");
        coordinatesPanel.add(joint2YLabel);

        joint3Label.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        joint3Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        joint3Label.setText("3");
        coordinatesPanel.add(joint3Label);

        joint3XLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        joint3XLabel.setText("0");
        coordinatesPanel.add(joint3XLabel);

        joint3YLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        joint3YLabel.setText("0");
        coordinatesPanel.add(joint3YLabel);

        brushLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        brushLabel.setText("Brush");
        coordinatesPanel.add(brushLabel);

        brushXLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        brushXLabel.setText("0");
        coordinatesPanel.add(brushXLabel);

        brushYLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        brushYLabel.setText("0");
        coordinatesPanel.add(brushYLabel);

        clearButton.setText("Clear Paint");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clearButton)
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(paintButton)))
                .addGap(44, 44, 44))
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(coordinatesPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jointButtonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(robotSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                .addContainerGap())
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(paintButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(clearButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coordinatesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jointButtonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(robotSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addComponent(controlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(41, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(controlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
                    .addGap(20, 20, 20)))
        );

        pack();
    }// </editor-fold>                        

    private void paintButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void j3RightButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void j2RightButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void j2LeftButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void j3LeftButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void j1RightButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void j1LeftButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void leftButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel brushLabel;
    private javax.swing.JLabel brushXLabel;
    private javax.swing.JLabel brushYLabel;
    private javax.swing.JButton clearButton;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JPanel coordinatesPanel;
    private javax.swing.JButton downButton;
    private javax.swing.JLabel j1Label;
    private javax.swing.JButton j1LeftButton;
    private javax.swing.JButton j1RightButton;
    private javax.swing.JLabel j2Label;
    private javax.swing.JButton j2LeftButton;
    private javax.swing.JButton j2RightButton;
    private javax.swing.JLabel j3Label;
    private javax.swing.JButton j3LeftButton;
    private javax.swing.JButton j3RightButton;
    private javax.swing.JLabel joint1Label;
    private javax.swing.JLabel joint1XLabel;
    private javax.swing.JLabel joint1YLabel;
    private javax.swing.JLabel joint2Label;
    private javax.swing.JLabel joint2XLabel;
    private javax.swing.JLabel joint2YLabel;
    private javax.swing.JLabel joint3Label;
    private javax.swing.JLabel joint3XLabel;
    private javax.swing.JLabel joint3YLabel;
    private javax.swing.JPanel jointButtonsPanel;
    private javax.swing.JLabel jointTitleLabel;
    private javax.swing.JButton leftButton;
    private javax.swing.JToggleButton paintButton;
    private javax.swing.JButton rightButton;
    private javax.swing.JSlider robotSlider;
    private javax.swing.JButton upButton;
    private javax.swing.JLabel xTitleLabel;
    private javax.swing.JLabel yTitleLabel;
    // End of variables declaration                   
}
